trigger:
  - main

pool:
  name: devops-agent

variables:
  terraformVersion: '1.14.6'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Prod'

stages:

- stage: Terraform_Init_Validate_Plan
  displayName: Terraform Init Validate Plan

  jobs:

  - job: TerraformPlan
    displayName: Terraform Plan

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(terraformVersion)

    - task: CmdLine@2
      displayName: Terraform Init
      inputs:
        script: |
          terraform init
        workingDirectory: $(workingDirectory)

    - task: CmdLine@2
      displayName: Terraform Validate
      inputs:
        script: |
          terraform validate
        workingDirectory: $(workingDirectory)

    - task: CmdLine@2
      displayName: Terraform Plan
      inputs:
        script: |
          terraform plan
        workingDirectory: $(workingDirectory)